// Generated by CodiumAI

describe("setMusic", () => {
  // correctly sets the music source to the selected song's path
  it("should set the music source to the selected song's path when a valid index is provided", () => {
    document.body.innerHTML = `
        <audio id="audio"></audio>
        <div class="bar"></div>
        <div class="artist"></div>
        <div class="square"></div>
        <div class="now"></div>
        <div class="period"></div>
      `;

    const songs = [
      {
        path: "song1.mp3",
        name: "Song 1",
        artist: "Artist 1",
        cover: "cover1.jpg",
      },
      {
        path: "song2.mp3",
        name: "Song 2",
        artist: "Artist 2",
        cover: "cover2.jpg",
      },
    ];

    global.songs = songs;
    const music = document.querySelector("#audio");
    const bar = document.querySelector(".bar");
    const artist = document.querySelector(".artist");
    const square = document.querySelector(".square");
    const now = document.querySelector(".now");
    const period = document.querySelector(".period");

    setMusic(1);

    expect(music.src).toContain("song2.mp3");
    expect(artist.innerHTML).toBe("Artist 2");
    expect(square.style.backgroundImage).toBe("url('cover2.jpg')");
  });

  // handles an invalid index gracefully
  it("should handle an invalid index gracefully by not changing the current music", () => {
    document.body.innerHTML = `
        <audio id="audio"></audio>
        <div class="bar"></div>
        <div class="artist"></div>
        <div class="square"></div>
        <div class="now"></div>
        <div class="period"></div>
      `;

    const songs = [
      {
        path: "song1.mp3",
        name: "Song 1",
        artist: "Artist 1",
        cover: "cover1.jpg",
      },
      {
        path: "song2.mp3",
        name: "Song 2",
        artist: "Artist 2",
        cover: "cover2.jpg",
      },
    ];

    global.songs = songs;
    const music = document.querySelector("#audio");
    const bar = document.querySelector(".bar");
    const artist = document.querySelector(".artist");
    const square = document.querySelector(".square");
    const now = document.querySelector(".now");
    const period = document.querySelector(".period");

    setMusic(0);

    expect(() => setMusic(5)).not.toThrow();
    expect(music.src).toContain("song1.mp3");
  });
});
